-- generated by tangling day3.org

import Data.Char

getFirstValue :: [Int] -> Int
getFirstValue = maximum . init

maxJolt :: [Int] -> Int
maxJolt xs =
  (maxValue * 10) + (getSecondValue maxValue xs)
  where maxValue = getFirstValue xs

getSecondValue :: Int -> [Int] -> Int
getSecondValue v xs = maximum $ tail $ dropWhile (/=v) xs

totalJoltage :: [[Int]] -> Int
totalJoltage xs = sum $ map maxJolt xs

day3_input = do
  input_data <- lines <$> readFile "day3_input.txt"
  let inputData = map (map digitToInt) input_data
  return inputData

day3_part1 :: IO Int
day3_part1 = fmap totalJoltage day3_input

getNextDigit :: [Int] -> (Int, [Int])
getNextDigit xs =
  (m, tail $ dropWhile (/=m) xs)
  where m = maximum xs

joltSeq :: [Int] -> [Int] -> [Int]
joltSeq [] _ = []
joltSeq xs [] = [maximum xs]
joltSeq xs reserve =
  (digit : joltSeq (t ++ [head reserve]) (tail reserve))
  where (digit,t) = getNextDigit xs

seqToInt :: [Int] -> Int
seqToInt = foldl (\acc x -> acc * 10 + x) 0

maxJolt' :: Int -> [Int] -> Int
maxJolt' digitCnt xs =
  seqToInt $ joltSeq digits reserve
  where (digits,reserve) = splitAt (length xs - (digitCnt-1)) xs

totalJoltage' :: [[Int]] -> Int
totalJoltage' xs = sum $ map (maxJolt' 12) xs

day3_part2 :: IO Int
day3_part2 = fmap totalJoltage' day3_input
